{% set name = "retriever" %}
{% set version = "2.3.1" %}
{% set sha256 = "b8a774a45db31e5ba4b693aabfa8c6ef958ea82187d5f97fd1d98d02da7ca540" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  entry_points:
    - retriever = retriever.__main__:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - numpydoc
  run:
    - python >=3.5
    - setuptools
    - xlrd
    - future
    - argcomplete
    - psycopg2-binary
    - pytest
    - pymysql
    - requests
    - tqdm
    - pandas

test:
  imports:
    - retriever
    - retriever.engines
    - retriever.lib

  requires:
    - pytest
  commands:
    - pytest -v -k "not postgres and not mysql and not spatial"
  source_files:
    - test/

about:
  home: https://github.com/weecology/retriever
  license: MIT
  summary: 'Data Retriever'
  license_family: MIT
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/weecology/retriever
  doc_url: https://retriever.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - Henrykironde
    - ethanwhite
    - zhangcandrew
