{% set name = "retriever" %}
{% set version = "2.2.0" %}
{% set sha256 = "8b195f70b04e89e7e3b1423e165271339e8dcc712c7f6d38daebb294d978f0a1" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  entry_points:
    - retriever = retriever.__main__:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - numpydoc
  run:
    - python >=3.5
    - setuptools
    - xlrd
    - future
    - argcomplete
    - psycopg2-binary
    - pytest
    - pymysql
    - requests
    - tqdm
    - pandas

test:
  imports:
    - retriever
    - retriever.engines
    - retriever.lib

about:
  home: https://github.com/weecology/retriever
  license: MIT
  summary: 'Data Retriever'
  license_family: MIT
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/weecology/retriever
  doc_url: https://retriever.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - Henrykironde
    - ethanwhite
    - zhangcandrew
