{% set name = "retriever" %}
{% set version = "2.1.0" %}
{% set sha256 = "c45cede0e672d9b13298dd881ac59cf1664804fb47a59fd7c0e6c8f27d5431c1" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - retriever = retriever.__main__:main
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - xlrd
    - future
  run:
    - python
    - setuptools
    - xlrd
    - future

test:
  imports:
    - retriever
    - retriever.engines
    - retriever.lib

  commands:
    - retriever --help

about:
  home: https://github.com/weecology/retriever
  license: MIT
  summary: 'Data Retriever'
  license_family: MIT

extra:
  recipe-maintainers:
    - Henrykironde
    - ethanwhite
