{% set name = "retriever" %}
{% set version = "3.1.0" %}
{% set sha256 = "d025ed69e006deefe7a4d98323d46a28f75dcddad47033d90cb4956aa01cd479" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  entry_points:
    - retriever = retriever.__main__:main
  number: 0
  script:
    - echo 'The Data Retriever is a package manager for data. It downloads, cleans, and stores publicly available data, so that analysts spend less time cleaning and managing data, and more time analyzing it.' > "README.md"
    - echo '' > "CHANGES.md"
    - python -m pip install --no-deps --ignore-installed .
  always_include_files:
    - README.md
    - CHANGES.md
requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - numpydoc
  run:
    - python >=3.5
    - setuptools
    - xlrd
    - future
    - argcomplete
    - pytest
    - pymysql
    - requests
    - tqdm==4.30.0
    - pandas
    - openpyxl
    - kaggle
    - psycopg2-binary
    - numpy
    - numpydoc
    - tables
    - h5py
    - Pillow
    - inquirer
    - coverage

test:
  imports:
    - retriever
    - retriever.engines
    - retriever.lib

  requires:
    - pytest
  commands:
    - pytest -v -k "not postgres and not mysql and integration"
  source_files:
    - test/
    - README.md

about:
  home: https://github.com/weecology/retriever
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data Retriever
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/weecology/retriever
  doc_url: https://retriever.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - zhangcandrew
    - ethanwhite
    - Henrykironde
