{% set name = "retriever" %}
{% set version = "2.1.0" %}
{% set sha256 = "a1f3c9a50369246fab6faa9915981e5b85e57745c52c6277ff5a2eab24cd2483" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - retriever = retriever.__main__:main
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpydoc
  run:
    - python
    - setuptools
    - xlrd
    - future
    - argcomplete
    - psycopg2
    - pytest
    - pymysql

test:
  imports:
    - retriever
    - retriever.engines
    - retriever.lib

about:
  home: https://github.com/weecology/retriever
  license: MIT
  summary: 'Data Retriever'
  license_family: MIT

extra:
  recipe-maintainers:
    - Henrykironde
    - ethanwhite
    - zhangcandrew
