travis:
  secure:
    BINSTAR_TOKEN: jSI8tg+no/wh+lrLYPyWwqfddAtYTUpmWFpbHpnFvDwU4UKDV9CrF9CTI+OjrcJd9MRBAZ4nPWk49vXmRicsAy/SCSzX1C3hk6Vo98ZQdd5Fe6g6si0FQIqe0J3526gOXWfv/00gi8AnGwAtaQeu+YkkCREH3T0Ka9+ei93ZQnvrbYmOdZ8Y/PvgLc4T4JfIa0iXjdLlxorPc6HuWy10EekXHxDaQWDNdXeDpt0bqNst+sLtITwq3b7mRxqaaa2dJMt/+cwsO1+4JqHjDB58sN+DCNNYscICb6cm3NAWP1i1CO8TbvwJqRAeQq3t4Wmzw8zngzmQoQZ2jXyf2iBaFL+mYxw8VarpNjFXW+hKFLVLigCC7NHvXy+zKgUqc1je99izkLRAGOPzPDIOamXBaLCUFYu+BTClgAwhzfbPuTlwUrvpFWyLCnQccAg9a7i2cICrdNM63xMrMlmf/sEwJ+hSMXbn+GKy0wVaP/rz/3VTVpmutZW4Hox4zx0Kt1ABnKWYBvbjPUD+txRcG013EiK+vObZzj7zyvicMXwTiO7qhg1F+mhJydvdUYLL0ywj674AguNEI1FxbDi6WQ+3SRcx4nnj2Y5vL80yDHY3NKqzJLfFbPd9SIcphEK8gxX25zQsSh7WTVKt1yLGMO+m7lsU/sMcGxMI+JqxSSBlh/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
