travis:
  secure:
    BINSTAR_TOKEN: Ai5Ls8hQABA80HCZsEFybOVKfiidrMGEOEqVcQTGhnYuA7aENvudMExDdnBx89W2JC1yXNFl936BxirWzLeu6X5acVPt15+H2ZOC0/+xcyPqi/2MNSqRQd2k0r4hN9u/GFr1HGQQd+qvO6j6jUBhQw/g8qNo/Fm3zrgLhktLcjk8A4IIybYHAMJkf9S2i7T5tRHa0Lvy3n29EyiqxXp8wgMDrPNCDbF4EgzqFdhT/rNFlvPwLD1GACXlbpW1dec2AF0aRx20k1DpX/sAmDhInQ3ninbyC58fkTeZUGkUCcEJE1ZrbzFQgKl+dnN3QjNKIkF39y7nDIWPun4FY36/jM0Lqizh2XAKDRKBr8hiRHwxOFj+5c7mvh4tX3zgbeSB5L1l/7SiUGTZkufvUxzhqs+FkuO0sYTMCsGfxI0SoIok1SXKHplgg4qsGd2KtfZUMQjn+wsbNF8i0w7BQ7HZ7s/V43YwyiNwqd+ZKDUITlENJ2NprYR8cEHT4GxJwNU+wrjQ7a5HjgFSZFnjB40Eswg2auDruXQZMR9k+E4pw7gn+s1xsmNw/ixNGFhTtTGmP1v4A8sj1lv5VxT3pvpr+5RRA9E1fZOumTtXbRMWbc1ibcocRbrCUFGHXFk7N+/2KlsYixqWVpQCVXIPrEGMXKlVjVaYhAhgVaiZZk3omvQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

docker:
  executable: docker
  image: condaforge/linux-anvil-comp7
  command: bash
  interactive: true
conda_forge_output_validation: true
